name: Generate Release APK

on:
  # 手動実行ボタン
  workflow_dispatch:
    
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Check out
      uses: actions/checkout@v1
    - name: Set up JDK
      uses: actions/setup-java@v1
      with:
        java-version: '17'
        distribution: 'liberica'
    
 
    # コマンドラインからAPKの作成。実行前に環境変数をGitHubActionsのSecretから取得
    - name: check APK
      run: ./gradlew check
   
    - name: build APK
      run: ./gradlew testDebugUnitTest

    - name: Upload apk file
      uses: actions/upload-artifact@v1
      with:
          name: apk
          path: app/build/outputs/apk/debug/app-debug.apk
